name: GitHub Info & System Details (Ubuntu & Windows)

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *" # Runs daily at 12 PM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  fetch-github-info:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get GitHub Information
        run: |
          echo "Repository Name: ${{ github.repository }}"
          echo "Build Name: ${{ github.run_id }}"
          echo "Execution Number: ${{ github.run_number }}"
          echo "Branch Name: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Triggered By: ${{ github.actor }}"

      - name: Get System Details (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          echo "OS Information:"
          cat /etc/os-release
          
          echo "Kernel Version:"
          uname -r
          
          echo "CPU Info:"
          lscpu
          
          echo "Memory Info:"
          free -h
          
          echo "Disk Usage:"
          df -h

      - name: Get System Details (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "OS Information:"
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
          
          echo "CPU Info:"
          wmic cpu get caption, deviceid, name, numberofcores, maxclockspeed
          
          echo "Memory Info:"
          wmic memorychip get capacity
          
          echo "Disk Usage:"
          wmic logicaldisk get caption, description, filesystem, freespace, size

      - name: Set Up Python (Ubuntu & Windows)
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Run Python Script
        run: python python_slicing.py # Replace with your script

  send_notification:
    needs: fetch-github-info
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        run: echo "GitHub Actions Run Completed" | mail -s "Execution Completed" rdinesh808@gmail.com
